version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: fixlink-postgres
    environment:
      POSTGRES_DB: fixlink_db
      POSTGRES_USER: eshop
      POSTGRES_PASSWORD: eshop
    ports:
      - "5432:5432"
    volumes:
      - fixlink_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fixlink-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fixlink.vn
      PGADMIN_DEFAULT_PASSWORD: Admin@123
    ports:
      - "5050:80"
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  fixlink_postgres_data:
