-- =============================================================================
-- FIXLINK - SCHEMA CƠ SỞ DỮ LIỆU NỀN
-- Phase 1 Core Entities with Standard Audit Columns & Extensible Architecture
-- =============================================================================

-- 1. BẢNG USERS (Tài khoản người dùng hệ thống)
CREATE TABLE IF NOT EXISTS users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(50)  NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    role          VARCHAR(20)  NOT NULL,
    status        VARCHAR(20)  NOT NULL DEFAULT 'ACTIVE',
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    BIGINT,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT,
    deleted_at    TIMESTAMP WITH TIME ZONE,
    deleted_by    BIGINT
);
CREATE INDEX IF NOT EXISTS idx_users_username ON users(username);
CREATE INDEX IF NOT EXISTS idx_users_role_status ON users(role, status);

-- 2. BẢNG CUSTOMER_PROFILES (Hồ sơ Khách hàng)
CREATE TABLE IF NOT EXISTS customer_profiles (
    user_id         BIGINT PRIMARY KEY,
    full_name       VARCHAR(100) NOT NULL,
    phone           VARCHAR(20)  NOT NULL UNIQUE,
    email           VARCHAR(100) NOT NULL UNIQUE,
    avatar_url      VARCHAR(255),
    membership_tier VARCHAR(20)  NOT NULL DEFAULT 'STANDARD',
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by      BIGINT,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by      BIGINT,
    deleted_at      TIMESTAMP WITH TIME ZONE,
    deleted_by      BIGINT,
    CONSTRAINT fk_customer_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

-- 3. BẢNG TECHNICIAN_PROFILES (Hồ sơ Thợ / Kỹ thuật viên)
CREATE TABLE IF NOT EXISTS technician_profiles (
    user_id             BIGINT PRIMARY KEY,
    full_name           VARCHAR(100) NOT NULL,
    phone               VARCHAR(20)  NOT NULL UNIQUE,
    email               VARCHAR(100) NOT NULL UNIQUE,
    citizen_id          VARCHAR(20)  NOT NULL UNIQUE,
    id_card_front_url   VARCHAR(500),
    id_card_back_url    VARCHAR(500),
    avatar_url          VARCHAR(255),
    bio                 TEXT,
    years_experience    INTEGER      DEFAULT 0,
    avg_rating          DECIMAL(3,2) DEFAULT 0.00,
    completed_jobs      INTEGER      DEFAULT 0,
    wallet_balance      DECIMAL(12,0) DEFAULT 0,
    verification_status VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    verified_at         TIMESTAMP WITH TIME ZONE,
    verified_by         VARCHAR(50),
    rejection_reason    TEXT,
    is_online           BOOLEAN      DEFAULT FALSE,
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by          BIGINT,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by          BIGINT,
    deleted_at          TIMESTAMP WITH TIME ZONE,
    deleted_by          BIGINT,
    CONSTRAINT fk_technician_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS idx_tech_verification_status ON technician_profiles(verification_status);
CREATE INDEX IF NOT EXISTS idx_tech_online_status ON technician_profiles(is_online);

-- 4. BẢNG TECHNICIAN_VERIFICATIONS (Lịch sử Xác minh KYC Thợ)
CREATE TABLE IF NOT EXISTS technician_verifications (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    technician_id     BIGINT       NOT NULL,
    admin_id          BIGINT,
    status            VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    citizen_id        VARCHAR(20)  NOT NULL,
    id_card_front_url VARCHAR(500),
    id_card_back_url  VARCHAR(500),
    rejection_reason  TEXT,
    notes             TEXT,
    verified_at       TIMESTAMP WITH TIME ZONE,
    created_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by        BIGINT,
    updated_at        TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by        BIGINT,
    deleted_at        TIMESTAMP WITH TIME ZONE,
    deleted_by        BIGINT,
    CONSTRAINT fk_tech_verify_technician FOREIGN KEY (technician_id) REFERENCES users(id),
    CONSTRAINT fk_tech_verify_admin FOREIGN KEY (admin_id) REFERENCES users(id)
);
CREATE INDEX IF NOT EXISTS idx_tech_verify_tech_id ON technician_verifications(technician_id);
CREATE INDEX IF NOT EXISTS idx_tech_verify_status ON technician_verifications(status);

-- 5. BẢNG SERVICE_CATEGORIES (Danh mục Ngành nghề Dịch vụ)
CREATE TABLE IF NOT EXISTS service_categories (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code          VARCHAR(50)  NOT NULL UNIQUE,
    name          VARCHAR(100) NOT NULL,
    description   TEXT,
    icon_url      VARCHAR(255),
    display_order INTEGER      DEFAULT 0,
    is_active     BOOLEAN      DEFAULT TRUE,
    created_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by    BIGINT,
    updated_at    TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by    BIGINT,
    deleted_at    TIMESTAMP WITH TIME ZONE,
    deleted_by    BIGINT
);
CREATE INDEX IF NOT EXISTS idx_categories_code ON service_categories(code);
CREATE INDEX IF NOT EXISTS idx_categories_active ON service_categories(is_active);

-- 6. BẢNG SERVICES (Chi tiết Gói dịch vụ sửa chữa)
CREATE TABLE IF NOT EXISTS services (
    id                         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id                BIGINT       NOT NULL,
    code                       VARCHAR(50)  NOT NULL UNIQUE,
    name                       VARCHAR(150) NOT NULL,
    description                TEXT,
    base_price                 DECIMAL(12,0) NOT NULL DEFAULT 0,
    estimated_duration_minutes INTEGER      DEFAULT 60,
    is_active                  BOOLEAN      DEFAULT TRUE,
    created_at                 TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by                 BIGINT,
    updated_at                 TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by                 BIGINT,
    deleted_at                 TIMESTAMP WITH TIME ZONE,
    deleted_by                 BIGINT,
    CONSTRAINT fk_services_category FOREIGN KEY (category_id) REFERENCES service_categories(id)
);
CREATE INDEX IF NOT EXISTS idx_services_category_id ON services(category_id);
CREATE INDEX IF NOT EXISTS idx_services_code ON services(code);

-- 7. BẢNG REPAIR_REQUESTS (Yêu cầu Sửa chữa Lõi)
CREATE TABLE IF NOT EXISTS repair_requests (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_code   VARCHAR(50)  NOT NULL UNIQUE,
    customer_id    BIGINT       NOT NULL,
    technician_id  BIGINT,
    category_id    BIGINT       NOT NULL,
    service_id     BIGINT,
    status         VARCHAR(30)  NOT NULL DEFAULT 'PENDING',
    title          VARCHAR(200) NOT NULL,
    description    TEXT         NOT NULL,
    address        VARCHAR(255) NOT NULL,
    requested_time TIMESTAMP WITH TIME ZONE NOT NULL,
    agreed_price   DECIMAL(12,0) DEFAULT 0,
    deposit_amount DECIMAL(12,0) DEFAULT 0,
    version        BIGINT       DEFAULT 0,
    created_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    created_by     BIGINT,
    updated_at     TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_by     BIGINT,
    deleted_at     TIMESTAMP WITH TIME ZONE,
    deleted_by     BIGINT,
    CONSTRAINT fk_repair_req_customer FOREIGN KEY (customer_id) REFERENCES users(id),
    CONSTRAINT fk_repair_req_technician FOREIGN KEY (technician_id) REFERENCES users(id),
    CONSTRAINT fk_repair_req_category FOREIGN KEY (category_id) REFERENCES service_categories(id),
    CONSTRAINT fk_repair_req_service FOREIGN KEY (service_id) REFERENCES services(id)
);
CREATE INDEX IF NOT EXISTS idx_repair_requests_customer ON repair_requests(customer_id);
CREATE INDEX IF NOT EXISTS idx_repair_requests_technician ON repair_requests(technician_id);
CREATE INDEX IF NOT EXISTS idx_repair_requests_status ON repair_requests(status);

-- 8. BẢNG AUDIT_LOGS (Nhật ký kiểm toán toàn hệ thống)
CREATE TABLE IF NOT EXISTS audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     BIGINT,
    action      VARCHAR(50)  NOT NULL,
    entity_name VARCHAR(50)  NOT NULL,
    entity_id   VARCHAR(50)  NOT NULL,
    old_values  TEXT,
    new_values  TEXT,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX IF NOT EXISTS idx_audit_logs_user_action ON audit_logs(user_id, action);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON audit_logs(entity_name, entity_id);
